blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature requests
    url: https://discuss.bitrise.io/c/feature-request/
    about: Share new feature ideas
  - name: â“ Ask a question
    url: https://discuss.bitrise.io/
    about: Ask any question you have
